# 网站的基本信息
site:
  tab: Naster17
  title: ☠️ Naster17
  description: Personal Blog | Dev Log
  language: en 
  favicon: /favicon.ico 
  theme: 
    light: winter 
    dark: dracula
    code: github-dark 
  date_format: ddd MMM DD YYYY 
  blog: 
    pageSize: 8 
  menu: 
    - id: home
      text: Home
      href: /
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: About
      href: /about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: blog
      text: Blogs
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
      subItems:
        - id: all
          text: All blogs
          href: /blog
          svg: "material-symbols:ink-pen-outline-rounded"
          target: _self
        - id: documentation
          text: Documentation
          href: /blog/category/Documentation
          svg: "material-symbols:unknown-document-outline-rounded"
          target: _self
        - id: examples
          text: Examples
          href: /blog/category/Examples
          svg: "material-symbols:deployed-code-outline"
          target: _self
        # 子菜单项配置
    - id: project
      text: Project
      href: /project
      svg: "material-symbols:code-blocks-outline"
      target: _self
    - id: friend
      text: Friend
      href: /friend
      svg: "material-symbols:supervisor-account-outline-rounded"
      target: _self
    - id: contact
      text: Contact
      href: "mailto:contact.evesunmaple@outlook.com"
      target: _blank # 在新标签页打开
      svg: "material-symbols:attach-email-outline-rounded"

# 用户的个人信息
user:
  name: Naster17 
  site: "https://naster17.github.io" 
  avatar: /profile.png 
  sidebar: 
    social:
      - href: "https://afdian.com/a/saroprock" 
        ariaLabel: Support my work
        title: Support my work 
        svg: "ri:cup-line"
      - href: "https://github.com/Naster17"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"

  footer:
    social:
      - href: "https://afdian.com/a/saroprock" 
        ariaLabel: Support my work 
        title: Support my work 
        svg: "ri:cup-line"
      - href: "https://github.com/EveSunMaple"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
